
#include "hilma/io/ply.h"

#define TINYPLY_IMPLEMENTATION
#include "hilma/io/tinyply.h"

#include <iostream> 
#include <fstream>

bool savePLY( const std::string& _filename, Mesh& _mesh, bool _binnary  ) {

    std::filebuf fb;
    fb.open(_filename.c_str(), std::ios::out | std::ios::binary);
    std::ostream outstream(&fb);
    if (outstream.fail()) throw std::runtime_error("failed to open " + _filename);

    tinyply::PlyFile file;

    file.add_properties_to_element("vertex", { "x", "y", "z" }, 
        tinyply::Type::FLOAT32, _mesh.vertices.size(), reinterpret_cast<uint8_t*>(_mesh.vertices.data()), tinyply::Type::INVALID, 0);

    if (_mesh.hasNormals())
        file.add_properties_to_element("vertex", { "nx", "ny", "nz" },
        tinyply::Type::FLOAT32, _mesh.normals.size(), reinterpret_cast<uint8_t*>(_mesh.normals.data()), tinyply::Type::INVALID, 0);

    if (_mesh.hasTexcoords())
        file.add_properties_to_element("vertex", { "u", "v" },
        tinyply::Type::FLOAT32, _mesh.texcoords.size() , reinterpret_cast<uint8_t*>(_mesh.texcoords.data()), tinyply::Type::INVALID, 0);

    if (_mesh.hasIndices())
        file.add_properties_to_element("face", { "vertex_indices" },
        tinyply::Type::UINT32, _mesh.indices.size(), reinterpret_cast<uint8_t*>(_mesh.indices.data()), tinyply::Type::UINT8, 3);

    file.get_comments().push_back("generated by tinyply 2.3");

    // Write file
    file.write(outstream, _binnary);

    return true;
}
